# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: 💬 Задать вопрос в Discussions
    url: https://github.com/storelike/open-source-storelike-ui/discussions
    about: Пожалуйста, используйте Discussions для общих вопросов, не связанных с ошибками или новыми функциями.

